services:
  db:
    image: postgres:15
    container_name: portfolio_postgres
    environment:
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_pass
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  migrate:
    build:
      context: .
    depends_on:
      - db
    entrypoint: >
      bash -c "
      alembic upgrade head
      "
    environment:
      - DATABASE_URL=postgresql://portfolio_user:portfolio_pass@db:5432/portfolio_db
    networks:
      - backend

  app:
    build:
      context: .
    depends_on:
      - db
      - migrate
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://portfolio_user:portfolio_pass@db:5432/portfolio_db
    command: streamlit run app.py --server.address=0.0.0.0
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:

