services:
  db:
    image: postgres:15
    container_name: portfolio_postgres
    environment:
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_pass
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  streamlit:
    build: .
    container_name: portfolio_streamlit
    depends_on:
      - db
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    environment:
      - DATABASE_URL=postgresql://portfolio_user:portfolio_pass@db:5432/portfolio_db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:

